[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "feature_blocks"
version = "1.0.0"
description = "Extract and cluster features from image blocks."
readme = "README.md"
requires-python = ">=3.11"
license = { file = "LICENSE.txt" }
dependencies = [
    "dask<=2024.11.2",
    "dask_image",
    "dask_jobqueue",
    "distributed",
    "typer",
    "numpy",
    "scikit-image",
    "transformers",
    "timm",
    "einops",
    "opencv-python",
    "shapely",
    "zarr==2.18.7",
    "spatial_image",
    "bokeh",
    "matplotlib",
    "ipycytoscape",
    "geopandas",
    "spatialdata==0.4.0",
    "rasterio",
    "cp-measure",
    "pycytominer",
    "toml",
    "ome-zarr",
]

[project.scripts]
feature_blocks = "feature_blocks.main:app"

# [project.optional-dependencies]
# cuda = [
#       "torch",
#       "torchvision==0.23.0",
# ]
# cpu = [
#       "torch",
#       "torchvision==0.23.0",
# ]
# dev = ["pytest", "black", "isort", "ruff", "ipykernel"]
# test = ["coverage"]

# [tool.uv]
# conflicts = [
#   [
#     { extra = "cpu" },
#     { extra = "cuda" },
#   ],
# ]

# # Index configuration
# [[tool.uv.index]]
# name = "pytorch-cpu"
# url = "https://download.pytorch.org/whl/cpu"
# explicit = true

# [[tool.uv.index]]
# name = "pytorch-cuda"
# url = "https://download.pytorch.org/whl/cu128"
# explicit = true

# # Source configuration - CPU by default, CUDA when extra is specified
# [tool.uv.sources]
# torch = [
#     { index = "pytorch-cuda", extra = 'cuda' },
#     { index = "pytorch-cpu", extra = 'cpu' },  # Default (no marker)
# ]
# torchvision = [
#     { index = "pytorch-cuda", extra = 'cuda' },
#     { index = "pytorch-cpu", extra = 'cpu' },  # Default (no marker)
# ]


[project.optional-dependencies]
cpu = [
  "torch>=2.7.0",
  "torchvision>=0.22.0",
]
cu128 = [
  "torch>=2.7.0",
  "torchvision>=0.22.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cu128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]
torchvision = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cu128", extra = "cu128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true